language:
  - c

sudo:
  - false

os:
  - linux
  - osx

addons:
  homebrew:
    update: true
    brewfile: true

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ctest --output-on-failure

